# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget_contacts = QtWidgets.QListWidget(self.widget)
        self.listWidget_contacts.setObjectName("listWidget_contacts")
        self.verticalLayout_2.addWidget(self.listWidget_contacts)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.addContact = QtWidgets.QPushButton(self.widget)
        self.addContact.setObjectName("addContact")
        self.horizontalLayout_2.addWidget(self.addContact)
        self.delContact = QtWidgets.QPushButton(self.widget)
        self.delContact.setObjectName("delContact")
        self.horizontalLayout_2.addWidget(self.delContact)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_message = QtWidgets.QListWidget(self.widget1)
        self.listWidget_message.setObjectName("listWidget_message")
        self.verticalLayout.addWidget(self.listWidget_message)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_message = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_message.setObjectName("lineEdit_message")
        self.horizontalLayout.addWidget(self.lineEdit_message)
        self.sendButton = QtWidgets.QPushButton(self.widget1)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.pushButtonUp = QtWidgets.QPushButton(self.widget1)
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.horizontalLayout.addWidget(self.pushButtonUp)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.console = QtWidgets.QListWidget(self.splitter_2)
        self.console.setObjectName("console")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.lineEdit_message.raise_()
        self.sendButton.raise_()
        self.splitter.raise_()
        self.addContact.raise_()
        self.delContact.raise_()
        self.console.raise_()
        self.listWidget_message.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.login = QtWidgets.QAction(MainWindow)
        self.login.setObjectName("login")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.login)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addContact.setText(_translate("MainWindow", "Добавить"))
        self.delContact.setText(_translate("MainWindow", "Удалить"))
        self.sendButton.setText(_translate("MainWindow", "Отправить"))
        self.pushButtonUp.setText(_translate("MainWindow", "Обновить"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.login.setText(_translate("MainWindow", "Вход"))
        self.action_2.setText(_translate("MainWindow", "Регистрация"))

