# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 827)
        MainWindow.setWindowOpacity(10.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(250)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.widget_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_contacts = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_contacts.sizePolicy().hasHeightForWidth())
        self.widget_contacts.setSizePolicy(sizePolicy)
        self.widget_contacts.setObjectName("widget_contacts")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_contacts)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabContacts = QtWidgets.QTabWidget(self.widget_contacts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabContacts.sizePolicy().hasHeightForWidth())
        self.tabContacts.setSizePolicy(sizePolicy)
        self.tabContacts.setMinimumSize(QtCore.QSize(0, 0))
        self.tabContacts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabContacts.setBaseSize(QtCore.QSize(200, 0))
        self.tabContacts.setObjectName("tabContacts")
        self.tab_contacts = QtWidgets.QWidget()
        self.tab_contacts.setObjectName("tab_contacts")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_contacts)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_contacts = QtWidgets.QListWidget(self.tab_contacts)
        self.listWidget_contacts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_contacts.setAlternatingRowColors(True)
        self.listWidget_contacts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listWidget_contacts.setIconSize(QtCore.QSize(0, 0))
        self.listWidget_contacts.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget_contacts.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget_contacts.setUniformItemSizes(True)
        self.listWidget_contacts.setBatchSize(100)
        self.listWidget_contacts.setObjectName("listWidget_contacts")
        self.gridLayout.addWidget(self.listWidget_contacts, 1, 0, 1, 1)
        self.lineEditSearch = QtWidgets.QLineEdit(self.tab_contacts)
        self.lineEditSearch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditSearch.setText("")
        self.lineEditSearch.setFrame(False)
        self.lineEditSearch.setDragEnabled(False)
        self.lineEditSearch.setClearButtonEnabled(True)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 0, 1, 1)
        self.tabContacts.addTab(self.tab_contacts, "")
        self.tab_chat = QtWidgets.QWidget()
        self.tab_chat.setObjectName("tab_chat")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_chat)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget_chat = QtWidgets.QListWidget(self.tab_chat)
        self.listWidget_chat.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_chat.setObjectName("listWidget_chat")
        self.gridLayout_2.addWidget(self.listWidget_chat, 1, 0, 1, 1)
        self.lineEdit_search_chat = QtWidgets.QLineEdit(self.tab_chat)
        self.lineEdit_search_chat.setFrame(False)
        self.lineEdit_search_chat.setObjectName("lineEdit_search_chat")
        self.gridLayout_2.addWidget(self.lineEdit_search_chat, 0, 0, 1, 1)
        self.tabContacts.addTab(self.tab_chat, "")
        self.verticalLayout_2.addWidget(self.tabContacts)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.addContact = QtWidgets.QPushButton(self.widget_contacts)
        self.addContact.setObjectName("addContact")
        self.horizontalLayout_4.addWidget(self.addContact)
        self.delContact = QtWidgets.QPushButton(self.widget_contacts)
        self.delContact.setObjectName("delContact")
        self.horizontalLayout_4.addWidget(self.delContact)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.widget_chat = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_chat.sizePolicy().hasHeightForWidth())
        self.widget_chat.setSizePolicy(sizePolicy)
        self.widget_chat.setObjectName("widget_chat")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_chat)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_message = QtWidgets.QListWidget(self.widget_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(250)
        sizePolicy.setHeightForWidth(self.listWidget_message.sizePolicy().hasHeightForWidth())
        self.listWidget_message.setSizePolicy(sizePolicy)
        self.listWidget_message.setBaseSize(QtCore.QSize(0, 0))
        self.listWidget_message.setMouseTracking(False)
        self.listWidget_message.setAccessibleName("")
        self.listWidget_message.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_message.setLineWidth(0)
        self.listWidget_message.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget_message.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_message.setAutoScroll(True)
        self.listWidget_message.setAutoScrollMargin(0)
        self.listWidget_message.setObjectName("listWidget_message")
        self.verticalLayout.addWidget(self.listWidget_message)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_message = QtWidgets.QTextEdit(self.widget_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.textEdit_message.sizePolicy().hasHeightForWidth())
        self.textEdit_message.setSizePolicy(sizePolicy)
        self.textEdit_message.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_message.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_message.setLineWidth(0)
        self.textEdit_message.setObjectName("textEdit_message")
        self.horizontalLayout.addWidget(self.textEdit_message)
        self.sendButton = QtWidgets.QPushButton(self.widget_chat)
        self.sendButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.sendButton.setAutoFillBackground(False)
        self.sendButton.setText("")
        self.sendButton.setIconSize(QtCore.QSize(23, 23))
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.console = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setObjectName("console")
        self.verticalLayout_3.addWidget(self.console)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.splitter.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.login = QtWidgets.QAction(MainWindow)
        self.login.setObjectName("login")
        self.registration = QtWidgets.QAction(MainWindow)
        self.registration.setObjectName("registration")
        self.security = QtWidgets.QAction(MainWindow)
        self.security.setCheckable(True)
        self.security.setChecked(False)
        self.security.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.security.setAutoRepeat(True)
        self.security.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.security.setIconVisibleInMenu(False)
        self.security.setObjectName("security")
        self.quit = QtWidgets.QAction(MainWindow)
        self.quit.setObjectName("quit")
        self.profile = QtWidgets.QAction(MainWindow)
        self.profile.setObjectName("profile")
        self.menu.addAction(self.login)
        self.menu.addAction(self.registration)
        self.menu.addSeparator()
        self.menu.addAction(self.security)
        self.menu.addSeparator()
        self.menu.addAction(self.profile)
        self.menu.addAction(self.quit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabContacts.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Messenger"))
        MainWindow.setAccessibleName(_translate("MainWindow", "ыуацуа"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.tabContacts.setTabText(self.tabContacts.indexOf(self.tab_contacts), _translate("MainWindow", "Контакты"))
        self.lineEdit_search_chat.setPlaceholderText(_translate("MainWindow", "поиск"))
        self.tabContacts.setTabText(self.tabContacts.indexOf(self.tab_chat), _translate("MainWindow", "Чаты"))
        self.addContact.setText(_translate("MainWindow", "Добавить"))
        self.delContact.setText(_translate("MainWindow", "Удалить"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.login.setText(_translate("MainWindow", "Вход"))
        self.registration.setText(_translate("MainWindow", "Регистрация"))
        self.security.setText(_translate("MainWindow", "шифровать сообщения"))
        self.quit.setText(_translate("MainWindow", "Отключиться"))
        self.profile.setText(_translate("MainWindow", "Открыть профиль"))

